/* ============================================================
   Selah — verse data
   Feed pool: World English Bible (public domain)
   Memory deck: curated for memorization, WEB + KJV bundled
   ============================================================ */

// ---- Feed pool (WEB) ----
window.POOL = [
 ["Genesis 1:1","In the beginning, God created the heavens and the earth."],
 ["Genesis 1:3","God said, “Let there be light,” and there was light."],
 ["Deuteronomy 31:6","Be strong and courageous. Don’t be afraid; for Yahweh your God goes with you. He will not fail you, nor forsake you."],
 ["Joshua 1:9","Be strong and courageous. Don’t be afraid. Don’t be dismayed, for Yahweh your God is with you wherever you go."],
 ["1 Samuel 16:7","Man looks at the outward appearance, but Yahweh looks at the heart."],
 ["Nehemiah 8:10","Don’t be grieved, for the joy of Yahweh is your strength."],
 ["Psalm 23:1","Yahweh is my shepherd; I shall lack nothing."],
 ["Psalm 23:4","Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me."],
 ["Psalm 27:1","Yahweh is my light and my salvation. Whom shall I fear?"],
 ["Psalm 34:18","Yahweh is near to those who have a broken heart, and saves those who have a crushed spirit."],
 ["Psalm 46:1","God is our refuge and strength, a very present help in trouble."],
 ["Psalm 46:10","Be still, and know that I am God."],
 ["Psalm 51:10","Create in me a clean heart, O God. Renew a right spirit within me."],
 ["Psalm 55:22","Cast your burden on Yahweh and he will sustain you. He will never allow the righteous to be moved."],
 ["Psalm 91:1","He who dwells in the secret place of the Most High will rest in the shadow of the Almighty."],
 ["Psalm 118:24","This is the day that Yahweh has made. We will rejoice and be glad in it!"],
 ["Psalm 119:105","Your word is a lamp to my feet, and a light for my path."],
 ["Psalm 121:2","My help comes from Yahweh, who made heaven and earth."],
 ["Psalm 139:14","I will give thanks to you, for I am fearfully and wonderfully made."],
 ["Psalm 147:3","He heals the broken in heart, and binds up their wounds."],
 ["Proverbs 3:5","Trust in Yahweh with all your heart, and don’t lean on your own understanding."],
 ["Proverbs 3:6","In all your ways acknowledge him, and he will make your paths straight."],
 ["Proverbs 4:23","Keep your heart with all diligence, for out of it is the wellspring of life."],
 ["Proverbs 16:3","Commit your deeds to Yahweh, and your plans shall succeed."],
 ["Proverbs 18:10","Yahweh’s name is a strong tower: the righteous run to him, and are safe."],
 ["Proverbs 27:17","Iron sharpens iron; so a man sharpens his friend’s countenance."],
 ["Ecclesiastes 3:1","For everything there is a season, and a time for every purpose under heaven."],
 ["Isaiah 26:3","You will keep whoever’s mind is steadfast in perfect peace, because he trusts in you."],
 ["Isaiah 40:31","Those who wait for Yahweh will renew their strength. They will mount up with wings like eagles."],
 ["Isaiah 41:10","Don’t be afraid, for I am with you. Don’t be dismayed, for I am your God. I will strengthen you."],
 ["Isaiah 43:2","When you pass through the waters, I will be with you, and through the rivers, they will not overflow you."],
 ["Isaiah 53:5","He was pierced for our transgressions. By his wounds we are healed."],
 ["Jeremiah 29:11","For I know the thoughts that I think toward you, thoughts of peace, and not of evil, to give you hope and a future."],
 ["Lamentations 3:22","It is because of Yahweh’s loving kindnesses that we are not consumed, because his compassion doesn’t fail."],
 ["Lamentations 3:23","They are new every morning. Great is your faithfulness."],
 ["Micah 6:8","He has shown you, O man, what is good. What does Yahweh require of you, but to act justly, to love mercy, and to walk humbly with your God?"],
 ["Zephaniah 3:17","Yahweh, your God, is among you, a mighty one who will save. He will rejoice over you with joy."],
 ["Matthew 5:14","You are the light of the world. A city located on a hill can’t be hidden."],
 ["Matthew 6:33","Seek first God’s Kingdom and his righteousness; and all these things will be given to you as well."],
 ["Matthew 6:34","Therefore don’t be anxious for tomorrow, for tomorrow will be anxious for itself."],
 ["Matthew 11:28","Come to me, all you who labor and are heavily burdened, and I will give you rest."],
 ["Matthew 19:26","With men this is impossible, but with God all things are possible."],
 ["Mark 9:23","All things are possible to him who believes."],
 ["Luke 1:37","For nothing spoken by God is impossible."],
 ["John 1:5","The light shines in the darkness, and the darkness hasn’t overcome it."],
 ["John 3:16","For God so loved the world, that he gave his one and only Son, that whoever believes in him should not perish, but have eternal life."],
 ["John 8:12","I am the light of the world. He who follows me will not walk in the darkness, but will have the light of life."],
 ["John 14:6","I am the way, the truth, and the life. No one comes to the Father, except through me."],
 ["John 14:27","Peace I leave with you. My peace I give to you. Don’t let your heart be troubled, neither let it be fearful."],
 ["John 16:33","In the world you have trouble; but cheer up! I have overcome the world."],
 ["Romans 5:8","But God commends his own love toward us, in that while we were yet sinners, Christ died for us."],
 ["Romans 8:28","We know that all things work together for good for those who love God."],
 ["Romans 8:31","If God is for us, who can be against us?"],
 ["Romans 12:2","Don’t be conformed to this world, but be transformed by the renewing of your mind."],
 ["Romans 15:13","Now may the God of hope fill you with all joy and peace in believing, that you may abound in hope."],
 ["1 Corinthians 10:13","No temptation has taken you except what is common to man. God is faithful, who will not allow you to be tempted above what you are able."],
 ["1 Corinthians 13:4","Love is patient and is kind. Love doesn’t envy. Love doesn’t brag, is not proud."],
 ["1 Corinthians 13:13","But now faith, hope, and love remain—these three. The greatest of these is love."],
 ["1 Corinthians 16:14","Let all that you do be done in love."],
 ["2 Corinthians 5:7","For we walk by faith, not by sight."],
 ["2 Corinthians 12:9","My grace is sufficient for you, for my power is made perfect in weakness."],
 ["Galatians 5:22","But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faith."],
 ["Galatians 6:9","Let us not be weary in doing good, for we will reap in due season, if we don’t give up."],
 ["Ephesians 2:8","For by grace you have been saved through faith, and that not of yourselves; it is the gift of God."],
 ["Ephesians 3:20","Now to him who is able to do exceedingly abundantly above all that we ask or think."],
 ["Ephesians 6:10","Be strong in the Lord, and in the strength of his might."],
 ["Philippians 4:6","In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God."],
 ["Philippians 4:7","And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus."],
 ["Philippians 4:8","Whatever things are true, whatever things are honorable, whatever things are pure—think about these things."],
 ["Philippians 4:13","I can do all things through Christ, who strengthens me."],
 ["Colossians 3:23","Whatever you do, work heartily, as for the Lord, and not for men."],
 ["1 Thessalonians 5:16","Rejoice always. Pray without ceasing. In everything give thanks."],
 ["2 Timothy 1:7","For God didn’t give us a spirit of fear, but of power, love, and self-control."],
 ["Hebrews 11:1","Now faith is assurance of things hoped for, proof of things not seen."],
 ["Hebrews 12:1","Let us run with perseverance the race that is set before us."],
 ["Hebrews 13:8","Jesus Christ is the same yesterday, today, and forever."],
 ["James 1:2","Count it all joy, my brothers, when you fall into various temptations."],
 ["James 1:5","But if any of you lacks wisdom, let him ask of God, who gives to all liberally and without reproach."],
 ["1 Peter 5:7","Casting all your worries on him, because he cares for you."],
 ["1 John 4:4","Greater is he who is in you than he who is in the world."],
 ["1 John 4:18","There is no fear in love; but perfect love casts out fear."],
 ["1 John 4:19","We love him, because he first loved us."],
 ["Revelation 21:4","He will wipe away every tear from their eyes. Death will be no more; neither will there be mourning, nor crying, nor pain, any more."],
 ["Psalm 19:1","The heavens declare the glory of God. The expanse shows his handiwork."],
 ["Psalm 37:4","Also delight yourself in Yahweh, and he will give you the desires of your heart."],
 ["Psalm 30:5","Weeping may stay for the night, but joy comes in the morning."],
 ["Psalm 16:8","I have set Yahweh always before me. Because he is at my right hand, I shall not be moved."],
 ["Proverbs 17:22","A cheerful heart makes good medicine, but a crushed spirit dries up the bones."],
 ["Isaiah 40:8","The grass withers, the flower fades; but the word of our God stands forever."],
 ["Matthew 5:16","Let your light shine before men, that they may see your good works."],
 ["Matthew 7:7","Ask, and it will be given you. Seek, and you will find. Knock, and it will be opened for you."],
 ["Luke 6:38","Give, and it will be given to you: good measure, pressed down, shaken together, and running over."],
 ["John 15:5","I am the vine. You are the branches. He who remains in me bears much fruit."],
 ["Acts 20:35","It is more blessed to give than to receive."],
 ["Romans 12:12","Rejoice in hope; endure in troubles; continue steadfastly in prayer."],
 ["Colossians 3:2","Set your mind on the things that are above, not on the things that are on the earth."],
 ["Joshua 24:15","As for me and my house, we will serve Yahweh."],
 ["Proverbs 15:1","A gentle answer turns away wrath, but a harsh word stirs up anger."],
 ["Jeremiah 17:7","Blessed is the man who trusts in Yahweh, and whose confidence is in Yahweh."],
 ["Matthew 28:20","Behold, I am with you always, even to the end of the age."],
 ["Galatians 2:20","It is no longer I that live, but Christ lives in me."],
 ["Philippians 1:6","He who began a good work in you will complete it until the day of Jesus Christ."],
 ["Psalm 62:1","My soul rests in God alone. My salvation is from him."],
 ["Isaiah 12:2","Behold, God is my salvation. I will trust, and will not be afraid."]
];

// ---- Memory deck (short, high-value verses for memorization) ----
// text keyed by translation so switching works offline for the deck.
window.MEMORY_VERSES = [
 {ref:"John 3:16", web:"For God so loved the world, that he gave his one and only Son, that whoever believes in him should not perish, but have eternal life.", kjv:"For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life."},
 {ref:"Philippians 4:13", web:"I can do all things through Christ, who strengthens me.", kjv:"I can do all things through Christ which strengtheneth me."},
 {ref:"Psalm 23:1", web:"Yahweh is my shepherd; I shall lack nothing.", kjv:"The LORD is my shepherd; I shall not want."},
 {ref:"Proverbs 3:5", web:"Trust in Yahweh with all your heart, and don’t lean on your own understanding.", kjv:"Trust in the LORD with all thine heart; and lean not unto thine own understanding."},
 {ref:"Joshua 1:9", web:"Be strong and courageous. Don’t be afraid, for Yahweh your God is with you wherever you go.", kjv:"Be strong and of a good courage; be not afraid, for the LORD thy God is with thee whithersoever thou goest."},
 {ref:"Isaiah 41:10", web:"Don’t be afraid, for I am with you. Don’t be dismayed, for I am your God. I will strengthen you.", kjv:"Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee."},
 {ref:"Romans 8:28", web:"We know that all things work together for good for those who love God.", kjv:"And we know that all things work together for good to them that love God."},
 {ref:"Philippians 4:6", web:"In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God.", kjv:"Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God."},
 {ref:"Matthew 6:33", web:"Seek first God’s Kingdom and his righteousness; and all these things will be given to you as well.", kjv:"But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you."},
 {ref:"Psalm 46:10", web:"Be still, and know that I am God.", kjv:"Be still, and know that I am God."},
 {ref:"John 14:6", web:"I am the way, the truth, and the life. No one comes to the Father, except through me.", kjv:"I am the way, the truth, and the life: no man cometh unto the Father, but by me."},
 {ref:"2 Corinthians 5:7", web:"For we walk by faith, not by sight.", kjv:"For we walk by faith, not by sight."},
 {ref:"1 Corinthians 16:14", web:"Let all that you do be done in love.", kjv:"Let all your things be done with charity."},
 {ref:"Galatians 5:22", web:"But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faith.", kjv:"But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith."},
 {ref:"Hebrews 11:1", web:"Now faith is assurance of things hoped for, proof of things not seen.", kjv:"Now faith is the substance of things hoped for, the evidence of things not seen."},
 {ref:"1 John 4:19", web:"We love him, because he first loved us.", kjv:"We love him, because he first loved us."},
 {ref:"Psalm 119:105", web:"Your word is a lamp to my feet, and a light for my path.", kjv:"Thy word is a lamp unto my feet, and a light unto my path."},
 {ref:"Isaiah 40:31", web:"Those who wait for Yahweh will renew their strength. They will mount up with wings like eagles.", kjv:"But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles."},
 {ref:"2 Timothy 1:7", web:"For God didn’t give us a spirit of fear, but of power, love, and self-control.", kjv:"For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind."},
 {ref:"1 Peter 5:7", web:"Casting all your worries on him, because he cares for you.", kjv:"Casting all your care upon him; for he careth for you."},
 {ref:"Philippians 4:8", web:"Whatever things are true, whatever things are honorable, whatever things are pure, think about these things.", kjv:"Whatsoever things are true, whatsoever things are honest, whatsoever things are pure, think on these things."},
 {ref:"Romans 12:2", web:"Don’t be conformed to this world, but be transformed by the renewing of your mind.", kjv:"And be not conformed to this world: but be ye transformed by the renewing of your mind."},
 {ref:"John 8:12", web:"I am the light of the world. He who follows me will have the light of life.", kjv:"I am the light of the world: he that followeth me shall have the light of life."},
 {ref:"Micah 6:8", web:"Act justly, love mercy, and walk humbly with your God.", kjv:"Do justly, and love mercy, and walk humbly with thy God."}
];
